<?php

namespace NBGraphics\NewsBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticles($state, $sort = 'DESC')
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.state = :state')
            ->orderBy('a.id', $sort)
            ->setParameter('state', $state)
            ->getQuery()
            ->getResult()
        ;
    }
}
