services:
    app.export:
        class: NBGraphics\CoreBundle\Services\Export\ExportDatas
        arguments: ['@doctrine.orm.entity_manager']
    app.import.csvtoarray:
        class: NBGraphics\CoreBundle\Services\Import\ConvertCsvToArray
    app.crud.create:
        class: NBGraphics\CoreBundle\Services\Crud\CreateDatas
        arguments: ['@doctrine.orm.entity_manager']
    app.crud.update:
        class: NBGraphics\CoreBundle\Services\Crud\UpdateDatas
        arguments: ['@doctrine.orm.entity_manager']
    app.crud.delete:
        class: NBGraphics\CoreBundle\Services\Crud\DeleteDatas
        arguments: ['@doctrine.orm.entity_manager']
    app.email.contact.form:
        class: NBGraphics\CoreBundle\Services\Email\EmailContactFormSystem
        arguments: ["@mailer", "@templating"]
    app.email.registration.form:
        class: NBGraphics\CoreBundle\Services\Email\EmailRegistrationFormSystem
        arguments: ["@mailer", "@templating"]
    app.listener.observation:
        class: NBGraphics\CoreBundle\EventListener\ObservationListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
    app.sitemap:
        class: NBGraphics\CoreBundle\Services\Sitemap\Sitemap
        arguments: ['@doctrine.orm.entity_manager','@router']