nb_graphics_front_site:
    resource: "@NBGraphicsFrontSiteBundle/Controller/"
    type:     annotation
    prefix:   /

nb_graphics_admin:
    resource: "@NBGraphicsAdminBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

nb_graphics_account:
    resource: "@NBGraphicsAdminBundle/Controller/Account/"
    type:     annotation
    prefix:   /account

nb_graphics_core:
    resource: "@NBGraphicsCoreBundle/Resources/config/routing.yml"
    prefix:   /

nb_graphics_user:
    resource: "@NBGraphicsUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"