nb_graphics_front_site:
    resource: "@NBGraphicsFrontSiteBundle/Controller/"
    type:     annotation
    prefix:   /

nb_graphics_admin:
    resource: "@NBGraphicsAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

nb_graphics_news:
    resource: "@NBGraphicsNewsBundle/Controller/"
    type:     annotation

nb_graphics_seo:
    resource: "@NBGraphicsSeoBundle/Controller/"
    type:     annotation

nb_graphics_core:
    resource: "@NBGraphicsCoreBundle/Controller/"
    type:     annotation

nb_graphics_user:
    resource: "@NBGraphicsUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@NBGraphicsUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"