nb_graphics_front_site_homepage:
    path:     /
    defaults: { _controller: NBGraphicsFrontSiteBundle:Main:homePage }

nb_graphics_front_site_interactivewebmap:
    path:     /webmap
    defaults: { _controller: NBGraphicsFrontSiteBundle:InteractiveWebMap:indexInteractiveWebMap }

nb_graphics_front_site_submitobservation:
    path:     /submitObservations
    defaults: { _controller: NBGraphicsFrontSiteBundle:SubmitObservation:submitObservation }
