services:
    seo.routes.load:
        class: NBGraphics\SeoBundle\Services\Routes\LoadRoutes
        arguments: ['@doctrine.orm.entity_manager','@router']
    seo.extension:
        class: NBGraphics\SeoBundle\Twig\Extension\SeoExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }