<?php

namespace NBGraphics\CoreBundle\Repository;

/**
 * ModerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerationRepository extends \Doctrine\ORM\EntityRepository
{
}
