<?php

namespace NBGraphics\CoreBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNewsletters($sort = 'DESC')
    {
        return $this
            ->createQueryBuilder('n')
            ->orderBy('n.id', $sort)
            ->getQuery()
            ->getResult()
        ;
    }

    public function exportAll()
    {
        return $this
            ->createQueryBuilder('n')
            ->getQuery()
            ->iterate()
        ;
    }
}
