<?php

namespace NBGraphics\CoreBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function exportAll()
    {
        return $this
            ->createQueryBuilder('a')
            ->getQuery()
            ->iterate()
        ;
    }
}
