<?php

namespace NBGraphics\CoreBundle\Repository;

use NBGraphics\CoreBundle\Entity\TAXREF;

/**
 * TAXREFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TAXREFRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDistinctFamilleQB()
    {
        return $this
            ->createQueryBuilder('t')
            ->groupBy('t.famille')
        ;
    }
}
